# Generated by Django 2.2.6 on 2019-10-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('birthday', models.DateField(auto_now=True, verbose_name='Birthday')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('datetime_published', models.DateTimeField(verbose_name='Published Date')),
                ('is_published', models.BooleanField(verbose_name='published?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
