# Generated by Django 2.2.6 on 2019-10-22 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 10, 22, 17, 8, 49, 636882), verbose_name='Birthday'),
        ),
    ]
