# Generated by Django 2.2.6 on 2019-11-03 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20191103_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='amount',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 3, 21, 48, 19, 434435), verbose_name='Birthday'),
        ),
    ]
