# Generated by Django 2.2.6 on 2019-11-04 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20191103_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('amount', models.IntegerField(default=0, max_length=255)),
            ],
            options={
                'verbose_name': 'TopTag',
                'verbose_name_plural': 'TopTags',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 4, 8, 21, 5, 825479), verbose_name='Birthday'),
        ),
    ]
