# Generated by Django 2.2.6 on 2019-11-04 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20191104_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('top_id', models.IntegerField(verbose_name='UserId')),
            ],
            options={
                'verbose_name': 'TopUser',
                'verbose_name_plural': 'TopUsers',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=0, upload_to='', verbose_name='Avatar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='askme@askme.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='loggin', max_length=255, verbose_name='Login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 4, 8, 58, 57, 865397, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
