# Generated by Django 2.2.6 on 2019-11-04 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20191104_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Login')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('birthday', models.DateField(default=datetime.datetime(2019, 11, 4, 21, 9, 43, 21326, tzinfo=utc), verbose_name='Birthday')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Profile', verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
