# Generated by Django 2.2.6 on 2019-11-04 21:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_auto_20191104_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 4, 21, 10, 53, 98611, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
