# Generated by Django 2.2.6 on 2019-11-05 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20191105_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 5, 7, 18, 15, 581214, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
