# Generated by Django 2.2.6 on 2019-11-05 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20191105_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 5, 7, 20, 17, 67524, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
