# Generated by Django 2.2.6 on 2019-11-05 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20191105_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.AddField(
            model_name='profile',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='Profile_dislike', to='question.DisLike'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Profile_like', to='question.Like'),
        ),
        migrations.AddField(
            model_name='question',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='question_dislike', to='question.DisLike'),
        ),
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='question_like', to='question.Like'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 5, 7, 34, 7, 132550, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
